# melpazoid <https://github.com/riscy/melpazoid> build checks.

name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Emacs
        run: |
          sudo apt-get -y install emacs 2>/dev/null || (sudo apt-get update && sudo apt-get -y install emacs)
          emacs --version
      - name: Ensure pip exists
        run: |
          command -v pip || sudo apt-get -y install python3-pip
      - name: Install and Update Melpazoid
        run: |
          ( cd ~/melpazoid 2>/dev/null && git checkout -- . && git pull --rebase ) || git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid 2>/dev/null
      - name: Run melpazoid
        env:
          RECIPE: (yadm :repo "seanfarley/yadm.el" :fetcher github)
          EXIST_OK: false
        # --load is the magic argument we need to make this work for podman, https://stackoverflow.com/a/77663132
        run: env LOCAL_REPO="$GITHUB_WORKSPACE" make -C ~/melpazoid DOCKER_OUTPUT="--quiet --load"
      - name: Install Eldev
        run: curl -fsSL "https://raw.github.com/doublep/eldev/master/webinstall/github-eldev" | sh
      - name: Eldev lint
        run: |
          eldev -p -dtT --color=always lint
